# Site settings
title: 情報リテラシー
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/lit" # the subpath of your site, e.g. /blog/
url: "https://infolit.uec.tmu.ac.jp" # the base hostname & protocol for your site

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks",
               "space_after_headers", "superscript", "tables", "with_toc_data"]
exclude: ["vendor", "Gemfile", "Gemfile.lock"]
